# Thanks to https://gitlab.com/martisak/latex-pipeline/

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

compile:
  image: kjarosh/latex:2023.1
  stage: build
  script:
    - apk add make python3 py3-pip
    - pip install pygments
    - make pdf
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - elaborato.pdf
    expire_in: 1 month

